server:
  port: ${port:@xbin-store-cloud-config.server.port@}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:@eureka.client.serviceUrl.defaultZone@}

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: ${git.uri:@spring.cloud.config.uri@}
          username: ${git.username:@spring.cloud.config.username@}
          password: ${git.password:@spring.cloud.config.password@}
          search-paths: ${git.paths:*}