server:
  port: ${port:@xbin-store-cloud-eureka.server.port@}

spring:
  application:
    name: eureka

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:@eureka.client.serviceUrl.defaultZone@}
  instance:
    hostname: ${hostname:xbin-store-cloud-eureka}
