server:
  port: ${port:@xbin-store-cloud-zuul.server.port@}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:@eureka.client.serviceUrl.defaultZone@}

spring:
  application:
    name: Zuul

