spring:
  application:
    name: admin-dashboard

server:
  port: ${port:@xbin-store-cloud-admin.server.port@}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:@eureka.client.serviceUrl.defaultZone@}
  instance:
    hostname: ${hostname:admin}
    prefer-ip-address: true
